-- INSERTION OF 500 ROWS OF MOCK DATA --
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '350');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '288');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '229');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '293');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '460');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '264');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '256');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '308');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '421');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '438');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '365');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '54');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '218');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '389');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '499');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '297');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '198');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '365');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '349');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '348');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '179');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '390');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '473');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '185');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '271');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '427');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '111');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '83');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '332');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '353');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '143');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '154');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '334');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '491');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '421');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '370');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '359');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '414');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '419');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '65');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '480');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '95');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '392');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '42');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '152');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '259');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '437');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '410');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '228');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '167');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '140');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '246');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '424');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '419');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '483');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '82');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '167');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '15');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '342');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '478');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '402');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '11');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '381');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '150');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '390');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '227');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '287');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '11');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '321');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '423');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '428');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '355');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '198');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '36');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '52');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '399');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '134');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '131');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '391');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '33');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '219');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '415');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '345');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '409');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '348');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '181');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '82');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '280');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '389');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '258');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '138');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '5');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '375');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '495');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '348');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '24');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '172');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '414');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '87');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '346');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '269');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '93');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '499');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '21');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '322');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '199');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '228');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '121');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '174');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '103');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '444');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '6');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '290');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '389');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '2');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '176');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '127');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '80');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '123');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '70');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '287');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '81');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '93');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '480');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '495');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '184');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '434');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '20');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '425');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '315');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '184');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '480');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '478');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '120');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '422');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '13');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '72');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '41');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '139');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '384');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '465');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '395');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '98');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '124');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '82');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '220');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '365');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '290');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '161');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '115');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '365');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '61');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '463');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '407');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '161');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '168');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '340');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '485');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '230');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '161');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '116');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '475');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '204');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '35');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '121');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '441');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '375');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '400');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '342');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '424');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '256');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '289');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '393');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '330');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '222');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '475');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '92');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '420');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '148');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '152');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '228');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '487');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '51');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '316');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '44');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '383');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '220');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '224');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '162');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '337');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '251');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '302');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '365');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '60');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '32');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '379');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '95');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '47');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '399');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '194');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '424');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '351');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '218');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '406');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '358');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '66');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '5');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '308');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '231');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '68');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '122');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '383');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '373');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '364');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '150');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '175');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '347');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '233');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '493');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '299');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '316');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '255');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '159');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '239');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '414');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '469');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '394');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '291');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '444');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '34');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '316');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '301');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '32');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '386');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '490');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '498');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '164');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '342');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '179');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '408');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '414');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '36');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '36');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '15');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '153');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '121');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '308');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '91');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '370');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '418');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '404');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '50');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '396');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '408');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '263');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '54');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '85');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '311');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '5');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '152');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '471');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '237');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '258');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '475');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '344');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '32');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '221');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '301');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '386');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '269');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '57');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '47');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '259');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '283');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '65');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '187');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '283');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '464');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '185');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '30');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '69');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '167');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '308');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '459');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '486');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '101');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '79');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '115');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '248');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '305');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '378');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '206');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '469');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '39');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '158');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '183');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '427');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '85');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '499');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '323');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '217');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '249');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '140');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '364');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '274');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '377');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '457');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '467');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '414');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '425');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '194');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '456');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '403');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '133');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '95');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '146');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '444');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '52');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '207');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '62');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '181');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '413');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '43');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '194');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '441');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '176');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '403');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '464');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '482');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '349');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '67');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '321');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '223');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '274');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '492');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '96');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '220');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '57');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '191');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '6');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '314');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '466');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '97');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '162');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '12');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '461');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '352');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '310');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '318');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '458');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '258');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '362');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '265');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '289');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '286');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '473');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '236');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '455');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '201');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '100');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '77');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '63');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '284');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '134');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '431');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '63');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '261');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '403');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '40');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '472');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '417');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '483');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '462');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '228');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '246');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '291');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '57');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '455');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '344');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '388');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '253');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '7');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '129');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '83');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '353');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '451');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '321');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '4');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '29');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '146');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '75');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '467');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '119');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '387');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '221');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '175');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '289');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '273');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '496');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '381');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '63');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '190');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '103');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '289');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '498');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '183');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '72');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '299');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '452');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '13');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '475');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '430');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '94');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '394');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '477');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '61');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '373');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '33');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '140');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '289');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '193');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '100');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '298');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '276');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '369');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '263');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '382');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '282');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '164');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '183');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '443');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '449');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '341');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '458');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '403');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '159');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '346');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '236');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '235');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '234');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '394');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '495');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '444');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '63');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '106');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '470');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '371');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '93');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '411');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '416');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '449');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '146');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '31');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '291');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '481');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '239');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '96');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '85');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '289');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '203');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '243');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '120');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '307');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '5');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '79');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '388');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '27');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '408');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '387');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '1');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '458');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '92');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '23');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '423');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '155');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '43');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '144');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '497');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Proxima Centauri', '445');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '91');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '300');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '481');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '50');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Arcturus', '271');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '21');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '30');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '480');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Deneb', '456');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '64');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '71');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '302');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Alpha Centauri', '32');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '301');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '372');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Rigel', '387');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Sirius', '367');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Polaris', '27');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Betelgeuse', '282');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Vega', '107');
INSERT INTO stellar_systems (system_name, star_id) VALUES ('Antares', '85');