-- INSERTION OF 500 ROWS OF MOCK DATA --
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Wakanda', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Atlantis', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Lemuria', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Elbonia', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Asgard', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Wakanda', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Gondor', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Narnia', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Lemuria', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Atlantis', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Asgard', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Atlantis', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Rivendell', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Wakanda', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Zamonia', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Rivendell', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Gondor', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Zamonia', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Gondor', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Avalon', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Elbonia', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Elbonia', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Wakanda', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Wakanda', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Avalon', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Asgard', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Zamonia', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Asgard', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Zamonia', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Gondor', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Wakanda', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Rivendell', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Rivendell', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Asgard', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Wakanda', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Wakanda', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Narnia', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Narnia', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Rivendell', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Lemuria', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Narnia', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Gondor', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Atlantis', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Lemuria', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Lemuria', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Gondor', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Lemuria', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Lemuria', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Lemuria', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Asgard', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Avalon', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Elbonia', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Elbonia', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Wakanda', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Atlantis', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Wakanda', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Gondor', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Wakanda', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Gondor', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Narnia', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Avalon', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Atlantis', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Wakanda', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Atlantis', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Elbonia', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Elbonia', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Wakanda', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Asgard', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Narnia', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Narnia', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Rivendell', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Lemuria', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Elbonia', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Lemuria', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Avalon', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Gondor', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Avalon', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Elbonia', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Elbonia', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Atlantis', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Gondor', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Wakanda', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Gondor', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Zamonia', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Rivendell', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Zamonia', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Elbonia', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Elbonia', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Rivendell', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Elbonia', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Asgard', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Gondor', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Avalon', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Wakanda', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Asgard', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Asgard', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Avalon', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Wakanda', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Elbonia', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Wakanda', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Gondor', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Narnia', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Narnia', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Rivendell', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Gondor', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Wakanda', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Wakanda', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Rivendell', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Gondor', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Wakanda', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Avalon', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Rivendell', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Rivendell', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Zamonia', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Atlantis', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Rivendell', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Elbonia', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Zamonia', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Asgard', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Elbonia', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Elbonia', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Gondor', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Elbonia', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Zamonia', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Wakanda', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Wakanda', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Atlantis', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Elbonia', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Asgard', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Atlantis', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Elbonia', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Rivendell', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Atlantis', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Gondor', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Rivendell', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Narnia', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Narnia', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Rivendell', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Elbonia', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Atlantis', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Wakanda', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Asgard', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Gondor', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Lemuria', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Atlantis', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Asgard', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Narnia', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Wakanda', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Avalon', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Wakanda', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Atlantis', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Asgard', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Gondor', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Atlantis', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Elbonia', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Zamonia', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Narnia', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Asgard', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Avalon', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Rivendell', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Zamonia', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Zamonia', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Avalon', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Asgard', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Elbonia', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Narnia', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Elbonia', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Narnia', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Atlantis', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Zamonia', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Lemuria', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Elbonia', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Narnia', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Narnia', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Asgard', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Wakanda', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Rivendell', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Narnia', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Avalon', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Avalon', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Narnia', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Wakanda', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Elbonia', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Gondor', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Asgard', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Avalon', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Asgard', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Gondor', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Atlantis', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Narnia', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Narnia', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Lemuria', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Gondor', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Narnia', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Zamonia', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Avalon', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Wakanda', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Narnia', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Lemuria', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Avalon', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Zamonia', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Elbonia', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Gondor', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Narnia', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Lemuria', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Rivendell', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Asgard', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Gondor', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Narnia', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Gondor', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Elbonia', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Atlantis', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Atlantis', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Wakanda', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Atlantis', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Elbonia', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Zamonia', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Zamonia', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Zamonia', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Zamonia', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Avalon', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Zamonia', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Avalon', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Elbonia', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Gondor', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Wakanda', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Narnia', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Avalon', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Asgard', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Wakanda', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Zamonia', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Wakanda', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Zamonia', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Narnia', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Wakanda', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Elbonia', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Wakanda', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Atlantis', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Atlantis', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Zamonia', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Atlantis', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Zamonia', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Rivendell', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Wakanda', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Elbonia', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Lemuria', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Avalon', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Elbonia', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Atlantis', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Asgard', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Wakanda', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Wakanda', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Rivendell', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Zamonia', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Wakanda', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Narnia', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Gondor', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Atlantis', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Asgard', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Zamonia', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Asgard', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Avalon', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Zamonia', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Lemuria', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Elbonia', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Gondor', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Asgard', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Atlantis', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Wakanda', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Elbonia', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Asgard', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Avalon', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Zamonia', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Atlantis', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Atlantis', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Zamonia', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Narnia', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Zamonia', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Rivendell', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Narnia', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Atlantis', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Narnia', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Lemuria', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Zamonia', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Gondor', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Zamonia', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Zamonia', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Lemuria', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Avalon', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Zamonia', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Atlantis', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Rivendell', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Lemuria', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Zamonia', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Asgard', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Rivendell', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Wakanda', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Avalon', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Lemuria', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Gondor', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Asgard', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Atlantis', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Gondor', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Atlantis', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Lemuria', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Wakanda', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Avalon', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Narnia', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Asgard', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Zamonia', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Narnia', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Narnia', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Wakanda', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Gondor', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Atlantis', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Avalon', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Lemuria', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Rivendell', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Narnia', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Narnia', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Wakanda', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Asgard', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Atlantis', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Narnia', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Elbonia', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Wakanda', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Zamonia', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Narnia', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Elbonia', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Atlantis', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Rivendell', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Elbonia', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Avalon', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Narnia', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Zamonia', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Asgard', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Asgard', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Rivendell', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Zamonia', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Atlantis', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Zamonia', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Zamonia', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Lemuria', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Asgard', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Lemuria', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Lemuria', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Asgard', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Atlantis', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Gondor', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Zamonia', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Elbonia', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Wakanda', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Zamonia', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Avalon', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Atlantis', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Lemuria', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Narnia', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Lemuria', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Asgard', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Elbonia', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Rivendell', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Elbonia', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Wakanda', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Gondor', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Asgard', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Narnia', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Wakanda', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Lemuria', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Rivendell', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Elbonia', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Atlantis', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Elbonia', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Rivendell', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Asgard', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Asgard', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Narnia', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Elbonia', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Lemuria', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Avalon', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Gondor', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Wakanda', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Zamonia', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Zamonia', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Elbonia', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Avalon', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Lemuria', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Rivendell', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Zamonia', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Asgard', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Asgard', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Lemuria', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Zamonia', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Wakanda', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Narnia', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Elbonia', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Atlantis', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Lemuria', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Wakanda', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Zamonia', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Wakanda', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Lemuria', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Narnia', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Lemuria', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Atlantis', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Avalon', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Elbonia', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Narnia', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Rivendell', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Lemuria', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Rivendell', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Lemuria', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Atlantis', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Lemuria', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Asgard', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Narnia', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Zamonia', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Atlantis', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Zamonia', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Avalon', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Asgard', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Narnia', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Wakanda', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Elbonia', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Rivendell', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Wakanda', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Avalon', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Elbonia', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Rivendell', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Avalon', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Zamonia', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Elbonia', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Rivendell', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Avalon', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Lemuria', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Gondor', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Wakanda', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Avalon', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Rivendell', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Rivendell', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Asgard', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Avalon', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Lemuria', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Lemuria', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Elbonia', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Narnia', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Narnia', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Asgard', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Avalon', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Wakanda', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Lemuria', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Lemuria', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Asgard', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Lemuria', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Lemuria', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Avalon', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Avalon', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Gondor', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Starlight Peak Observatory', 'Gondor', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Rivendell', 'reflecting');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Asgard', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Zamonia', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Lemuria', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Asgard', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Wakanda', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Asgard', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Gondor', 'infrared');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Lemuria', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Atlantis', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Wakanda', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Zamonia', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Narnia', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Narnia', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Wakanda', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Wakanda', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Narnia', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Atlantis', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Gondor', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Wakanda', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Avalon', 'compound');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Atlantis', 'refractor');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Zamonia', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Wakanda', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Zamonia', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Celestial View Observatory', 'Rivendell', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Wakanda', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Zamonia', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Cosmos Watch Observatory', 'Lemuria', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Lemuria', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Lemuria', 'interferometer');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Elbonia', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Gondor', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Zamonia', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Skyward Vision Observatory', 'Narnia', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Astronomy Haven Observatory', 'Rivendell', 'optical');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Lunar Eclipse Observatory', 'Asgard', 'radio');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Aurora Borealis Observatory', 'Lemuria', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Rivendell', 'gamma-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Galaxy Watch Observatory', 'Avalon', 'X-ray');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Nebula Watch Observatory', 'Elbonia', 'ultraviolet');
INSERT INTO stellar_observatories (observatory_name, country, telescope_type) VALUES ('Stargazer Observatory', 'Rivendell', 'optical');