-- INSERTION OF 500 ROWS OF MOCK DATA --
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('238', 'Betelgeuse', '1332.17', '3625.87', 'close', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('303', 'Arcturus', '3899.1', '2388.25', 'far', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('294', 'Sirius', '678.42', '4651.71', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('11', 'Proxima Centauri', '3910.19', '3728.96', 'short', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('47', 'Proxima Centauri', '1474.78', '1268.96', 'medium', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('238', 'Proxima Centauri', '4235.86', '2820.96', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('231', 'Antares', '4001.7', '3194.48', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('368', 'Arcturus', '2788.08', '165.67', 'remote', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('341', 'Rigel', '1290.89', '962.37', 'long', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('199', 'Sirius', '2900.35', '3138.46', 'remote', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('286', 'Sirius', '2054.26', '3830.96', 'far', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('112', 'Alpha Centauri', '3120.21', '2448.6', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('217', 'Alpha Centauri', '2336.8', '3138.13', 'close', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('213', 'Antares', '4543.59', '4479.02', 'long', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('183', 'Arcturus', '3573.04', '2545.78', 'close', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('198', 'Alpha Centauri', '2551.71', '4013.31', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('65', 'Alpha Centauri', '2938.33', '3423.07', 'short', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('141', 'Alpha Centauri', '3304.65', '1481.28', 'distant', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('15', 'Sirius', '4477.29', '4623.1', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('158', 'Betelgeuse', '3015.22', '1678.18', 'distant', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('67', 'Vega', '3225.29', '3046.23', 'remote', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('33', 'Arcturus', '1095.39', '1531.39', 'medium', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('106', 'Proxima Centauri', '4439.19', '4466.33', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('346', 'Arcturus', '776.81', '827.55', 'proximal', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('232', 'Proxima Centauri', '1819.91', '1148.68', 'proximal', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('125', 'Alpha Centauri', '2017.21', '1843.25', 'close', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('16', 'Arcturus', '3651.84', '2628.73', 'short', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('399', 'Polaris', '1522.88', '2697.24', 'distant', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('7', 'Polaris', '1373.29', '784.69', 'distant', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('325', 'Deneb', '2974.27', '3007.41', 'short', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('283', 'Polaris', '1081.09', '3691.95', 'near', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('79', 'Sirius', '2171.85', '749.81', 'adjacent', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('273', 'Proxima Centauri', '2782.03', '1568.27', 'close', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('56', 'Antares', '1691.98', '2720.58', 'near', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('284', 'Antares', '311.08', '582.44', 'short', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('266', 'Vega', '2651.39', '2259.23', 'remote', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('34', 'Sirius', '3996.48', '1648.87', 'proximal', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('385', 'Proxima Centauri', '134.1', '2469.96', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('305', 'Betelgeuse', '1319.91', '2128.46', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('102', 'Antares', '3660.0', '3037.96', 'distant', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('395', 'Rigel', '3675.08', '4989.64', 'long', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('155', 'Rigel', '634.31', '879.81', 'medium', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('98', 'Sirius', '4371.86', '4970.51', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('266', 'Betelgeuse', '4589.12', '1187.22', 'proximal', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('9', 'Betelgeuse', '182.93', '109.55', 'proximal', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('266', 'Deneb', '1143.49', '4883.17', 'close', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('275', 'Alpha Centauri', '1631.65', '1965.31', 'near', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('299', 'Alpha Centauri', '1207.52', '676.34', 'remote', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('330', 'Alpha Centauri', '1218.03', '1035.52', 'short', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('305', 'Antares', '3617.5', '656.26', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('197', 'Antares', '2377.69', '1962.7', 'near', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('61', 'Proxima Centauri', '377.28', '3523.38', 'proximal', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('330', 'Rigel', '3532.89', '262.23', 'remote', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('365', 'Vega', '1768.04', '4110.18', 'proximal', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('97', 'Proxima Centauri', '4065.09', '2067.39', 'remote', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('205', 'Sirius', '3641.09', '1601.98', 'long', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('53', 'Deneb', '3684.57', '2533.93', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('269', 'Alpha Centauri', '3530.55', '1737.24', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('206', 'Sirius', '3670.07', '4252.68', 'short', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('243', 'Polaris', '389.98', '4594.6', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('354', 'Proxima Centauri', '4585.82', '1169.63', 'proximal', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('225', 'Alpha Centauri', '2915.5', '2909.14', 'close', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('265', 'Deneb', '1616.98', '744.35', 'proximal', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('237', 'Vega', '2663.19', '2053.56', 'short', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('241', 'Alpha Centauri', '1823.1', '2922.52', 'distant', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('94', 'Sirius', '3659.95', '4089.98', 'short', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('5', 'Rigel', '1576.48', '1340.82', 'short', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('101', 'Vega', '53.34', '4907.24', 'distant', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('154', 'Vega', '1590.11', '332.37', 'short', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('137', 'Alpha Centauri', '974.01', '4793.08', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('183', 'Betelgeuse', '4714.92', '1112.91', 'close', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('5', 'Alpha Centauri', '3167.4', '1558.17', 'near', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('205', 'Rigel', '378.43', '1887.39', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('8', 'Sirius', '204.21', '4061.61', 'short', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('194', 'Betelgeuse', '3974.61', '138.94', 'close', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('48', 'Alpha Centauri', '4995.4', '988.35', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('324', 'Deneb', '4108.94', '1183.19', 'remote', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('108', 'Vega', '3738.8', '2921.6', 'close', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('165', 'Betelgeuse', '3619.47', '490.99', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('341', 'Polaris', '3290.91', '1584.82', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('392', 'Sirius', '959.2', '3566.84', 'short', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('43', 'Polaris', '1473.24', '4511.4', 'remote', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('379', 'Alpha Centauri', '1198.85', '2557.49', 'proximal', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('184', 'Alpha Centauri', '1021.97', '2977.79', 'distant', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('22', 'Vega', '4950.66', '2069.93', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('199', 'Sirius', '3390.49', '3499.74', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('36', 'Polaris', '942.57', '4543.13', 'proximal', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('211', 'Rigel', '3142.8', '1857.95', 'long', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('247', 'Deneb', '1933.68', '4500.32', 'proximal', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('101', 'Betelgeuse', '493.69', '4403.46', 'short', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('139', 'Antares', '500.07', '4855.48', 'proximal', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('350', 'Alpha Centauri', '2598.33', '4444.25', 'distant', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('40', 'Vega', '1354.8', '3392.09', 'distant', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('152', 'Alpha Centauri', '1170.98', '4736.2', 'medium', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('205', 'Proxima Centauri', '2322.32', '832.2', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('328', 'Alpha Centauri', '738.4', '3714.48', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('220', 'Betelgeuse', '1682.04', '19.17', 'proximal', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('172', 'Polaris', '2103.43', '2901.66', 'close', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('264', 'Deneb', '4571.83', '628.48', 'proximal', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('97', 'Arcturus', '2473.71', '1626.17', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('306', 'Sirius', '2683.76', '3381.41', 'close', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('41', 'Vega', '796.77', '4492.13', 'remote', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('278', 'Polaris', '2538.76', '3614.47', 'long', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('206', 'Proxima Centauri', '3453.06', '3709.76', 'proximal', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('240', 'Betelgeuse', '2606.31', '3015.42', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('379', 'Rigel', '3962.86', '2555.93', 'short', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('265', 'Deneb', '2428.57', '2984.94', 'medium', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('362', 'Alpha Centauri', '4022.81', '4069.49', 'close', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('26', 'Betelgeuse', '2731.19', '3465.41', 'adjacent', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('103', 'Sirius', '4515.98', '668.28', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('391', 'Sirius', '2075.67', '1602.66', 'remote', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('143', 'Arcturus', '4932.8', '4960.43', 'close', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('18', 'Alpha Centauri', '1998.13', '4432.13', 'medium', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('81', 'Rigel', '1159.67', '3249.64', 'close', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('31', 'Sirius', '2215.88', '3311.84', 'distant', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('200', 'Deneb', '2380.71', '3684.42', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('339', 'Alpha Centauri', '3410.31', '1003.96', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('185', 'Antares', '1539.16', '2331.04', 'adjacent', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('244', 'Sirius', '4363.88', '3270.02', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('321', 'Polaris', '2323.14', '2241.81', 'medium', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('188', 'Arcturus', '622.03', '1437.09', 'long', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('80', 'Alpha Centauri', '1639.11', '676.93', 'medium', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('67', 'Arcturus', '105.46', '2233.79', 'remote', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('61', 'Alpha Centauri', '795.29', '4387.48', 'long', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('97', 'Polaris', '4138.94', '379.74', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('11', 'Sirius', '1029.8', '2293.92', 'proximal', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('227', 'Antares', '826.66', '78.59', 'close', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('308', 'Deneb', '667.59', '1830.1', 'short', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('6', 'Sirius', '4718.51', '678.07', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('386', 'Proxima Centauri', '3079.79', '1740.19', 'medium', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('388', 'Deneb', '1947.84', '3594.37', 'short', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('122', 'Sirius', '4434.5', '1224.46', 'long', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('236', 'Arcturus', '796.25', '3135.98', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('177', 'Vega', '4937.33', '3234.88', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('252', 'Antares', '931.21', '4076.73', 'far', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('178', 'Deneb', '3844.37', '1777.15', 'medium', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('91', 'Polaris', '3118.02', '600.37', 'medium', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('340', 'Proxima Centauri', '1671.3', '2878.35', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('327', 'Rigel', '276.95', '4175.14', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('360', 'Betelgeuse', '4918.35', '591.41', 'far', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('348', 'Proxima Centauri', '3292.26', '3326.85', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('35', 'Sirius', '768.84', '736.17', 'close', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('360', 'Deneb', '4845.99', '3890.21', 'short', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('255', 'Sirius', '1712.68', '285.91', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('354', 'Arcturus', '2072.77', '852.28', 'long', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('118', 'Rigel', '3054.78', '466.51', 'proximal', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('218', 'Alpha Centauri', '4270.15', '1927.66', 'distant', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('50', 'Polaris', '60.21', '2667.52', 'far', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('365', 'Rigel', '3346.6', '2715.62', 'remote', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('239', 'Polaris', '1666.78', '4161.96', 'distant', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('222', 'Betelgeuse', '175.33', '474.15', 'medium', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('294', 'Betelgeuse', '4332.36', '846.82', 'close', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('1', 'Betelgeuse', '640.86', '3075.28', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('392', 'Rigel', '18.08', '1467.08', 'proximal', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('185', 'Antares', '2110.15', '849.74', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('65', 'Alpha Centauri', '1660.7', '95.32', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('169', 'Arcturus', '4754.02', '4029.28', 'long', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('187', 'Deneb', '1025.66', '1896.92', 'distant', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('160', 'Alpha Centauri', '1954.03', '310.25', 'far', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('294', 'Deneb', '3173.43', '1427.82', 'distant', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('50', 'Betelgeuse', '124.24', '727.49', 'long', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('172', 'Vega', '1093.22', '4644.65', 'adjacent', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('261', 'Betelgeuse', '3231.89', '1503.05', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('137', 'Alpha Centauri', '619.01', '1685.7', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('226', 'Polaris', '2237.83', '82.25', 'short', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('93', 'Rigel', '1331.64', '3249.49', 'short', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('246', 'Polaris', '215.3', '2747.22', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('64', 'Rigel', '4346.6', '1467.76', 'short', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('246', 'Proxima Centauri', '1268.83', '4104.16', 'adjacent', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('22', 'Sirius', '1594.88', '753.12', 'medium', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('208', 'Polaris', '3115.0', '4876.85', 'short', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('166', 'Sirius', '1980.69', '937.34', 'proximal', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('226', 'Proxima Centauri', '4281.64', '2237.56', 'proximal', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('354', 'Betelgeuse', '1710.62', '3698.38', 'distant', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('328', 'Rigel', '4789.02', '3655.99', 'short', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('170', 'Sirius', '1633.67', '4771.33', 'close', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('184', 'Sirius', '3825.23', '4747.48', 'medium', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('376', 'Proxima Centauri', '2618.21', '4820.63', 'close', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('90', 'Antares', '3760.97', '4688.5', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('198', 'Sirius', '4482.53', '160.96', 'short', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('132', 'Antares', '2508.85', '3730.13', 'long', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('94', 'Deneb', '2776.92', '4018.43', 'far', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('70', 'Antares', '4930.35', '4401.88', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('398', 'Sirius', '2654.83', '2340.1', 'adjacent', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('31', 'Arcturus', '3939.11', '1464.82', 'short', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('349', 'Arcturus', '3312.22', '1948.55', 'near', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('359', 'Deneb', '1303.76', '1808.0', 'proximal', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('72', 'Betelgeuse', '4019.26', '1842.68', 'short', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('65', 'Alpha Centauri', '3077.16', '2385.95', 'distant', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('370', 'Vega', '4110.36', '856.42', 'proximal', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('8', 'Arcturus', '2037.71', '2502.89', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('359', 'Antares', '687.2', '3760.72', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('392', 'Sirius', '3851.42', '4206.32', 'remote', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('195', 'Deneb', '4079.36', '1481.99', 'remote', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('91', 'Deneb', '4221.76', '3537.57', 'medium', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('161', 'Deneb', '4768.61', '4470.5', 'adjacent', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('306', 'Arcturus', '1475.79', '4772.55', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('26', 'Sirius', '4031.62', '3341.46', 'short', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('14', 'Sirius', '4171.52', '520.43', 'short', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('305', 'Deneb', '352.58', '3517.35', 'short', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('327', 'Rigel', '3279.44', '2619.77', 'long', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('34', 'Arcturus', '991.1', '1150.35', 'remote', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('177', 'Betelgeuse', '1113.23', '2898.26', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('177', 'Antares', '1697.77', '1171.21', 'long', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('163', 'Rigel', '2687.91', '921.13', 'proximal', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('164', 'Arcturus', '2264.05', '555.48', 'medium', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('178', 'Sirius', '1594.26', '2190.39', 'long', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('37', 'Betelgeuse', '90.3', '2836.74', 'far', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('316', 'Arcturus', '995.47', '866.97', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('190', 'Antares', '4422.2', '4543.13', 'short', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('65', 'Vega', '1325.46', '1846.21', 'remote', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('223', 'Rigel', '473.11', '4581.69', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('89', 'Sirius', '1724.8', '869.92', 'proximal', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('238', 'Antares', '1219.99', '2375.13', 'long', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('396', 'Sirius', '3247.96', '4269.04', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('156', 'Sirius', '1819.52', '3456.1', 'long', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('393', 'Proxima Centauri', '4707.95', '1290.08', 'proximal', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('188', 'Polaris', '518.4', '2791.43', 'remote', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('57', 'Proxima Centauri', '1481.76', '671.58', 'near', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('89', 'Arcturus', '3288.77', '4852.39', 'proximal', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('258', 'Rigel', '484.0', '161.37', 'far', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('211', 'Polaris', '3303.83', '2854.63', 'long', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('319', 'Alpha Centauri', '1687.58', '2578.45', 'proximal', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('12', 'Rigel', '4294.12', '1317.56', 'distant', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('211', 'Proxima Centauri', '4523.97', '4199.74', 'proximal', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('248', 'Arcturus', '3456.04', '3279.0', 'distant', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('179', 'Proxima Centauri', '1356.55', '975.09', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('348', 'Antares', '2732.32', '4295.86', 'distant', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('115', 'Proxima Centauri', '4075.51', '346.6', 'long', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('320', 'Antares', '772.42', '1381.8', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('13', 'Alpha Centauri', '1969.09', '2444.95', 'proximal', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('346', 'Antares', '1978.37', '3847.88', 'medium', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('165', 'Alpha Centauri', '89.47', '4973.73', 'adjacent', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('380', 'Betelgeuse', '4848.86', '3556.57', 'short', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('76', 'Polaris', '2641.56', '4120.38', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('249', 'Rigel', '4900.73', '3954.7', 'adjacent', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('133', 'Arcturus', '2884.84', '3068.64', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('118', 'Betelgeuse', '4006.29', '4619.81', 'close', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('115', 'Polaris', '4462.56', '1610.8', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('394', 'Betelgeuse', '1022.49', '1703.15', 'medium', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('295', 'Betelgeuse', '115.11', '4028.49', 'distant', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('41', 'Proxima Centauri', '3488.87', '941.41', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('91', 'Antares', '3795.59', '3550.52', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('147', 'Arcturus', '1776.33', '720.09', 'medium', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('397', 'Antares', '3573.36', '3590.87', 'near', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('177', 'Deneb', '858.74', '1884.25', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('21', 'Proxima Centauri', '3405.27', '2691.59', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('321', 'Rigel', '1221.84', '4151.54', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('25', 'Polaris', '4436.44', '47.82', 'distant', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('220', 'Arcturus', '4172.81', '4557.14', 'proximal', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('250', 'Betelgeuse', '4584.79', '2537.86', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('275', 'Proxima Centauri', '2967.67', '3412.89', 'close', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('84', 'Vega', '1691.62', '1483.51', 'close', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('359', 'Rigel', '3848.28', '2473.15', 'proximal', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('163', 'Rigel', '3531.91', '4305.73', 'long', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('65', 'Polaris', '4591.99', '1898.28', 'close', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('179', 'Arcturus', '2338.43', '709.79', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('252', 'Antares', '4974.41', '1794.9', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('54', 'Rigel', '813.11', '1107.25', 'near', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('218', 'Arcturus', '525.72', '899.22', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('353', 'Proxima Centauri', '1860.63', '702.25', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('16', 'Betelgeuse', '3034.87', '3852.58', 'proximal', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('300', 'Arcturus', '163.98', '1265.05', 'long', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('362', 'Deneb', '524.02', '4533.0', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('396', 'Vega', '1964.63', '1188.79', 'proximal', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('187', 'Antares', '2786.05', '3537.94', 'proximal', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('381', 'Sirius', '3623.91', '3721.97', 'long', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('337', 'Alpha Centauri', '4127.21', '1298.13', 'medium', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('230', 'Alpha Centauri', '4414.32', '2425.74', 'long', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('14', 'Vega', '4578.3', '4598.35', 'medium', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('23', 'Rigel', '609.76', '3195.81', 'far', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('187', 'Betelgeuse', '194.56', '3080.23', 'near', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('168', 'Vega', '3406.62', '1036.55', 'long', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('375', 'Proxima Centauri', '2316.85', '2232.68', 'near', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('157', 'Polaris', '3931.12', '4518.36', 'proximal', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('311', 'Vega', '2277.51', '3504.29', 'close', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('127', 'Rigel', '2701.89', '4188.02', 'medium', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('264', 'Vega', '4229.42', '3631.58', 'close', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('111', 'Betelgeuse', '4744.56', '701.17', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('17', 'Deneb', '4171.47', '4091.49', 'long', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('303', 'Arcturus', '1583.55', '541.87', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('361', 'Vega', '498.38', '642.38', 'proximal', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('175', 'Alpha Centauri', '472.11', '122.73', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('154', 'Sirius', '903.75', '19.16', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('390', 'Deneb', '536.98', '1272.16', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('290', 'Rigel', '2431.52', '1662.51', 'remote', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('11', 'Arcturus', '2691.18', '913.27', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('174', 'Alpha Centauri', '2761.53', '1586.75', 'adjacent', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('154', 'Polaris', '577.44', '4306.47', 'far', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('112', 'Deneb', '28.66', '3648.74', 'distant', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('274', 'Vega', '4364.58', '2270.3', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('286', 'Betelgeuse', '2759.8', '4375.83', 'close', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('213', 'Betelgeuse', '1887.98', '2372.14', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('306', 'Deneb', '1485.85', '2649.88', 'proximal', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('126', 'Arcturus', '2019.52', '1229.76', 'long', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('93', 'Arcturus', '2155.45', '2796.74', 'short', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('44', 'Proxima Centauri', '3223.66', '1815.53', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('324', 'Deneb', '3922.29', '1029.12', 'adjacent', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('324', 'Betelgeuse', '4351.6', '1775.7', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('69', 'Arcturus', '4092.14', '4923.45', 'long', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('363', 'Antares', '1906.24', '1549.75', 'medium', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('238', 'Proxima Centauri', '1030.46', '1566.05', 'medium', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('372', 'Sirius', '1868.79', '1514.47', 'distant', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('94', 'Sirius', '2611.2', '1073.33', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('277', 'Sirius', '1997.23', '352.49', 'adjacent', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('291', 'Arcturus', '4312.84', '288.09', 'close', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('323', 'Vega', '715.38', '928.85', 'medium', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('132', 'Vega', '3517.74', '2130.68', 'close', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('132', 'Vega', '3574.29', '3815.69', 'short', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('50', 'Antares', '2434.09', '4612.44', 'distant', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('133', 'Rigel', '779.51', '3777.47', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('323', 'Sirius', '708.3', '2602.35', 'distant', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('157', 'Vega', '3486.44', '4546.43', 'short', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('100', 'Betelgeuse', '2.2', '1514.05', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('89', 'Antares', '3665.07', '3740.6', 'long', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('312', 'Arcturus', '3645.76', '1822.83', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('295', 'Vega', '4681.81', '930.06', 'proximal', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('248', 'Rigel', '2003.9', '2753.28', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('58', 'Arcturus', '4829.66', '3359.71', 'medium', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('108', 'Arcturus', '3271.7', '4480.88', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('51', 'Arcturus', '988.39', '3489.04', 'proximal', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('50', 'Antares', '928.88', '891.18', 'remote', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('355', 'Proxima Centauri', '3683.26', '1215.05', 'distant', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('243', 'Vega', '525.91', '2858.94', 'distant', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('202', 'Deneb', '4548.22', '3823.36', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('231', 'Arcturus', '2409.07', '148.44', 'close', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('118', 'Deneb', '2011.65', '4272.72', 'close', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('323', 'Arcturus', '3846.95', '3488.97', 'distant', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('172', 'Antares', '1396.41', '925.86', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('377', 'Betelgeuse', '4717.68', '3598.9', 'distant', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('224', 'Proxima Centauri', '2783.82', '2632.33', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('79', 'Deneb', '2740.21', '2769.51', 'medium', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('123', 'Rigel', '1404.78', '908.47', 'proximal', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('64', 'Antares', '4555.93', '2995.59', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('96', 'Deneb', '2008.77', '3838.22', 'close', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('95', 'Alpha Centauri', '3786.57', '2382.58', 'close', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('170', 'Polaris', '3353.09', '555.65', 'long', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('73', 'Antares', '2356.95', '3726.15', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('213', 'Betelgeuse', '2852.36', '78.61', 'short', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('228', 'Alpha Centauri', '4550.44', '2967.0', 'medium', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('256', 'Betelgeuse', '2651.76', '517.79', 'distant', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('142', 'Rigel', '457.94', '163.51', 'distant', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('343', 'Rigel', '3008.9', '3801.29', 'distant', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('396', 'Sirius', '1392.24', '2520.26', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('142', 'Arcturus', '2605.95', '2332.39', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('298', 'Arcturus', '1626.35', '809.97', 'distant', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('396', 'Deneb', '2276.58', '313.6', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('254', 'Vega', '1229.61', '1402.51', 'distant', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('3', 'Polaris', '3617.21', '987.13', 'near', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('62', 'Betelgeuse', '2865.85', '3710.51', 'close', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('182', 'Sirius', '865.4', '3851.34', 'medium', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('183', 'Proxima Centauri', '2545.98', '4275.82', 'long', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('192', 'Arcturus', '3586.32', '3485.15', 'far', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('159', 'Proxima Centauri', '370.29', '2225.59', 'long', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('276', 'Deneb', '1742.82', '1880.02', 'close', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('215', 'Alpha Centauri', '2665.02', '1036.86', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('344', 'Vega', '3662.93', '3103.83', 'long', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('115', 'Deneb', '1.19', '3953.65', 'long', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('286', 'Rigel', '4228.3', '2263.32', 'medium', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('125', 'Arcturus', '1337.94', '2597.31', 'short', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('102', 'Betelgeuse', '4138.42', '4426.98', 'proximal', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('66', 'Polaris', '475.24', '2426.51', 'adjacent', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('323', 'Rigel', '2257.84', '3684.46', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('56', 'Deneb', '526.84', '2869.2', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('226', 'Deneb', '924.15', '3426.4', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('389', 'Sirius', '3859.92', '349.2', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('167', 'Polaris', '4668.86', '1967.16', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('241', 'Vega', '1363.29', '4068.33', 'long', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('286', 'Sirius', '2357.99', '3039.05', 'proximal', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('77', 'Arcturus', '4893.94', '2321.12', 'long', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('301', 'Rigel', '2434.08', '4868.4', 'distant', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('296', 'Antares', '3975.43', '1136.68', 'near', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('125', 'Sirius', '269.04', '40.82', 'long', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('188', 'Betelgeuse', '4139.92', '2438.58', 'close', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('94', 'Rigel', '1089.96', '4765.86', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('111', 'Proxima Centauri', '1150.57', '3409.27', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('317', 'Arcturus', '943.58', '4104.9', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('139', 'Antares', '325.84', '4852.89', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('32', 'Sirius', '4293.65', '4705.33', 'far', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('8', 'Sirius', '44.95', '324.42', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('253', 'Betelgeuse', '1782.56', '4463.63', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('48', 'Antares', '905.79', '4006.32', 'close', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('140', 'Sirius', '2536.96', '4657.48', 'close', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('91', 'Vega', '4671.28', '1358.89', 'near', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('304', 'Rigel', '1503.54', '1197.29', 'close', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('76', 'Polaris', '58.89', '4842.34', 'distant', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('180', 'Vega', '2555.02', '3019.69', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('69', 'Proxima Centauri', '2357.99', '1343.5', 'adjacent', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('169', 'Alpha Centauri', '786.32', '2237.5', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('66', 'Proxima Centauri', '926.27', '3588.03', 'medium', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('96', 'Alpha Centauri', '2956.72', '2404.55', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('67', 'Sirius', '1806.59', '952.08', 'medium', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('13', 'Alpha Centauri', '1611.7', '4956.37', 'near', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('265', 'Vega', '4128.15', '3001.06', 'distant', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('63', 'Proxima Centauri', '1894.34', '2352.55', 'distant', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('152', 'Alpha Centauri', '4112.42', '2101.25', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('137', 'Betelgeuse', '449.71', '2912.48', 'medium', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('249', 'Alpha Centauri', '2245.77', '2853.06', 'medium', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('109', 'Antares', '1144.06', '4649.44', 'long', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('193', 'Alpha Centauri', '2670.58', '3093.12', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('246', 'Deneb', '2997.38', '1150.69', 'adjacent', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('396', 'Antares', '2154.34', '246.72', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('277', 'Alpha Centauri', '1704.74', '1995.96', 'adjacent', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('274', 'Arcturus', '1187.28', '172.56', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('399', 'Polaris', '438.61', '4881.85', 'proximal', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('355', 'Sirius', '192.02', '2825.48', 'long', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('145', 'Arcturus', '987.76', '3291.93', 'remote', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('380', 'Alpha Centauri', '639.64', '298.77', 'near', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('282', 'Vega', '114.88', '2898.39', 'remote', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('137', 'Deneb', '1385.84', '106.0', 'far', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('388', 'Sirius', '3193.94', '295.47', 'medium', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('329', 'Arcturus', '3322.32', '3155.65', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('52', 'Antares', '4490.88', '2114.8', 'medium', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('243', 'Vega', '2213.39', '572.64', 'medium', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('296', 'Sirius', '732.99', '4626.03', 'remote', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('52', 'Sirius', '460.52', '3400.8', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('26', 'Rigel', '4632.6', '3790.33', 'medium', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('365', 'Polaris', '3076.1', '1007.45', 'medium', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('64', 'Betelgeuse', '4703.67', '1882.96', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('72', 'Arcturus', '40.37', '1583.69', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('396', 'Betelgeuse', '2726.95', '721.06', 'long', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('186', 'Proxima Centauri', '3664.68', '4798.24', 'close', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('348', 'Vega', '715.77', '3233.85', 'remote', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('252', 'Alpha Centauri', '851.62', '1075.38', 'short', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('306', 'Betelgeuse', '2605.08', '2589.41', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('24', 'Betelgeuse', '4376.44', '811.42', 'proximal', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('87', 'Vega', '1776.8', '752.61', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('135', 'Rigel', '4074.65', '3951.75', 'far', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('384', 'Alpha Centauri', '2270.9', '3054.82', 'adjacent', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('196', 'Rigel', '2620.74', '2331.74', 'close', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('248', 'Antares', '4890.41', '2793.15', 'close', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('309', 'Arcturus', '2886.21', '4375.31', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('19', 'Proxima Centauri', '4887.73', '4238.29', 'medium', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('91', 'Polaris', '3903.17', '969.51', 'proximal', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('319', 'Deneb', '1655.49', '3700.72', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('256', 'Betelgeuse', '2384.71', '1934.52', 'far', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('220', 'Arcturus', '2347.7', '4597.94', 'long', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('347', 'Proxima Centauri', '1027.42', '1532.05', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('41', 'Rigel', '2544.23', '3867.88', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('343', 'Sirius', '4979.7', '2531.95', 'long', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('24', 'Arcturus', '3879.01', '145.15', 'close', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('159', 'Deneb', '3399.82', '3550.38', 'short', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('128', 'Rigel', '3789.67', '343.91', 'close', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('215', 'Polaris', '1282.03', '1727.2', 'proximal', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('235', 'Arcturus', '1336.04', '3299.29', 'short', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('130', 'Antares', '1242.63', '1205.25', 'short', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('110', 'Alpha Centauri', '4007.62', '3534.11', 'medium', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('89', 'Proxima Centauri', '552.31', '2320.25', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('202', 'Arcturus', '3137.88', '1441.86', 'distant', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('276', 'Antares', '2130.93', '686.06', 'near', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('7', 'Betelgeuse', '732.0', '43.45', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('81', 'Sirius', '2283.73', '2059.83', 'close', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('158', 'Deneb', '1703.81', '1295.73', 'short', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('273', 'Betelgeuse', '4948.96', '4313.93', 'long', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('215', 'Antares', '936.31', '53.01', 'long', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('43', 'Arcturus', '1331.07', '3002.12', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('265', 'Polaris', '429.59', '4561.98', 'medium', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('170', 'Betelgeuse', '388.64', '2209.28', 'remote', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('377', 'Betelgeuse', '2788.11', '3183.59', 'short', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('107', 'Polaris', '1871.1', '465.98', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('357', 'Betelgeuse', '3037.87', '1638.37', 'far', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('121', 'Proxima Centauri', '1454.43', '2748.24', 'close', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('331', 'Antares', '996.58', '4696.91', 'close', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('77', 'Betelgeuse', '2618.48', '3732.71', 'proximal', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('27', 'Deneb', '1031.55', '3129.66', 'short', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('4', 'Vega', '2513.45', '3937.8', 'remote', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('189', 'Proxima Centauri', '3751.98', '3152.0', 'near', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('82', 'Rigel', '1285.11', '4402.96', 'short', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('204', 'Polaris', '557.1', '3562.29', 'distant', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('46', 'Vega', '181.83', '917.61', 'remote', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('25', 'Rigel', '2666.32', '4526.4', 'proximal', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('328', 'Vega', '4282.15', '3241.35', 'long', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('364', 'Sirius', '2930.86', '2212.9', 'proximal', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('31', 'Betelgeuse', '2508.62', '1634.15', 'close', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('310', 'Arcturus', '4885.36', '3368.96', 'medium', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('203', 'Deneb', '3724.41', '426.69', 'distant', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('383', 'Deneb', '691.01', '2052.46', 'adjacent', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('103', 'Antares', '4623.04', '2519.82', 'adjacent', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('262', 'Antares', '2584.48', '4450.0', 'near', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('13', 'Proxima Centauri', '2705.44', '2939.11', 'medium', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('72', 'Sirius', '386.6', '837.43', 'adjacent', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('38', 'Alpha Centauri', '3820.27', '963.93', 'proximal', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('256', 'Alpha Centauri', '1352.04', '2116.37', 'close', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('202', 'Proxima Centauri', '2387.83', '4029.73', 'far', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('306', 'Deneb', '222.4', '4770.39', 'long', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('118', 'Proxima Centauri', '1924.91', '2866.41', 'short', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('38', 'Betelgeuse', '1914.39', '2026.44', 'remote', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('283', 'Rigel', '3685.84', '4077.81', 'remote', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('293', 'Deneb', '188.28', '3702.88', 'adjacent', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('199', 'Deneb', '207.58', '1540.43', 'medium', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('258', 'Vega', '4697.43', '2207.98', 'medium', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('265', 'Alpha Centauri', '2831.1', '893.24', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('381', 'Proxima Centauri', '4577.35', '3636.9', 'short', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('270', 'Alpha Centauri', '4779.01', '1914.93', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('237', 'Arcturus', '1196.47', '2792.47', 'near', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('39', 'Sirius', '1671.96', '3719.66', 'medium', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('178', 'Proxima Centauri', '4374.54', '2406.98', 'proximal', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('92', 'Deneb', '1759.77', '4646.87', 'far', 'Y');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('152', 'Rigel', '3586.52', '367.23', 'far', 'N');
INSERT INTO stellar_galaxy_info (planet_id, star_system, galaxy_lat, galaxy_long, distance_band, planet_habitable) VALUES ('166', 'Rigel', '3094.89', '3549.68', 'remote', 'N');