-- INSERTION OF 500 ROWS OF MOCK DATA --
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '29', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '153', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '255', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '210', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '33', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '142', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '286', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '2', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '220', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '182', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '142', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '56', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '224', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '139', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '207', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '68', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '74', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '104', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '38', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '281', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '41', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '278', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '17', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '136', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '130', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '97', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '189', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '209', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '146', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '178', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '248', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '51', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '62', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '201', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '284', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '215', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '109', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '85', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '36', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '110', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '45', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '131', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '37', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '258', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '300', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '47', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '140', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '39', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '296', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '9', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '30', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '199', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '68', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '43', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '231', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '280', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '14', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '12', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '235', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '116', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '60', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '106', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '163', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '265', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '219', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '210', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '237', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '286', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '117', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '288', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '161', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '97', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '300', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '44', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '50', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '217', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '206', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '132', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '285', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '163', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '168', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '105', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '53', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '65', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '68', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '170', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '82', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '262', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '223', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '258', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '86', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '207', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '262', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '138', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '265', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '89', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '254', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '125', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '10', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '191', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '32', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '26', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '125', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '134', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '242', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '287', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '213', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '288', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '247', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '53', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '281', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '53', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '282', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '164', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '57', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '210', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '106', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '102', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '73', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '39', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '94', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '115', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '83', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '36', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '41', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '24', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '92', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '113', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '174', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '7', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '68', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '11', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '56', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '84', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '107', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '226', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '73', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '181', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '125', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '192', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '274', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '159', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '6', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '42', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '41', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '294', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '268', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '101', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '207', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '111', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '265', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '30', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '231', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '188', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '192', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '51', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '189', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '285', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '18', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '4', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '246', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '69', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '147', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '98', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '275', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '86', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '8', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '224', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '273', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '58', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '67', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '158', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '30', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '163', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '255', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '11', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '21', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '281', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '288', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '132', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '82', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '118', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '187', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '21', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '273', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '159', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '12', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '262', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '56', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '287', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '95', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '264', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '266', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '121', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '135', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '60', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '82', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '265', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '131', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '73', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '144', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '97', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '121', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '23', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '257', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '292', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '145', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '252', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '281', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '240', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '145', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '93', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '186', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '20', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '21', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '244', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '17', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '136', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '140', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '193', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '7', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '54', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '26', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '127', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '24', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '146', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '49', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '181', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '120', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '279', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '281', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '159', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '267', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '131', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '116', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '75', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '210', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '239', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '104', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '30', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '6', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '202', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '50', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '224', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '25', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '142', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '196', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '297', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '37', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '285', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '216', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '163', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '212', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '240', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '50', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '272', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '278', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '45', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '129', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '18', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '228', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '12', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '187', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '46', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '256', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '57', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '12', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '113', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '175', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '286', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '171', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '64', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '197', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '191', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '86', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '29', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '230', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '50', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '5', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '141', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '128', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '9', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '80', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '231', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '43', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '291', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '213', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '196', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '197', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '244', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '25', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '83', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '71', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '119', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '158', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '55', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '110', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '109', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '133', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '266', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '49', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '179', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '165', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '122', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '281', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '250', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '24', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '40', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '86', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '56', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '90', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '171', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '181', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '95', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '243', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '235', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '192', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '44', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '155', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '147', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '46', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '207', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '36', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '263', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '219', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '104', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '260', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '216', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '116', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '200', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '193', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '149', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '151', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '95', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '268', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '244', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '272', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '140', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '236', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '140', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '180', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '131', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '9', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '169', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '199', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '236', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '106', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '32', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '72', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '27', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '76', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '245', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '187', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '226', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '261', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '51', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '142', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '91', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '76', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '244', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '226', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '229', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '58', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '36', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '293', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '114', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '270', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '24', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '12', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '32', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '27', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '243', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '166', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '267', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '281', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '274', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '193', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '29', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '72', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '299', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '206', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '67', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '32', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '178', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '1', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '21', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '65', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '106', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '282', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '160', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '132', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '100', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '137', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '145', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '176', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '64', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '160', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '200', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '64', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '242', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '179', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '156', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '283', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '35', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '3', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '172', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '97', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '268', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '174', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '205', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '6', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '51', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '42', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '84', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '262', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '138', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '118', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '52', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mars', '81', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '231', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '79', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '8', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '50', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '194', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '222', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '225', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '77', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '29', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '247', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '212', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '106', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '20', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '20', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '148', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '60', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '240', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '10', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '79', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '188', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '252', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '97', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '181', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '108', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '256', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '102', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '35', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '117', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '226', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '46', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '113', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '235', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '133', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '217', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '247', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '118', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '27', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '23', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '252', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '28', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '35', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '175', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '223', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '83', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '221', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '27', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '121', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '36', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Mercury', '84', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '4', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '238', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '106', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '257', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '261', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '94', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '288', 'Vega');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '32', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '92', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '57', 'Proxima Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '164', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '275', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '195', 'Altair');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '49', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '189', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '278', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '64', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '209', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '86', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '186', 'Alpha Centauri');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '235', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '254', 'Antares');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Venus', '237', 'Sirius');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '121', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Saturn', '157', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Uranus', '116', 'Polaris');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '24', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Zorblax', '293', 'Deneb');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Earth', '151', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Pluto', '121', 'Fomalhaut');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Neptune', '101', 'Betelgeuse');
INSERT INTO stellar_planets (planet_name, host_star, star_system) VALUES ('Jupiter', '55', 'Deneb');