-- INSERTION OF 500 ROWS OF MOCK DATA --
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '1481', 'Nebula Navigators', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '2425', 'Orbit Explorers', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '2115', 'Celestial Explorations', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '1474', 'Stellar Ventures', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '2474', 'Galaxy Seekers', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '4820', 'Galactic Explorers', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '1365', 'Orbit Explorers', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '3844', 'Cosmic Discoveries', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '1280', 'Celestial Explorations', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '4748', 'Cosmic Discoveries', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '3449', 'Nebula Navigators', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '1919', 'Astro Quest', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '4578', 'Nebula Navigators', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '3920', 'Stellar Ventures', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '3970', 'Orbit Explorers', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '4586', 'Starlight Ventures', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '2392', 'Galaxy Seekers', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '2859', 'Interstellar Expeditions', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '3640', 'Interstellar Expeditions', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '1607', 'Interstellar Expeditions', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '2965', 'Stellar Ventures', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '4184', 'Cosmic Discoveries', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '3585', 'Nebula Navigators', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '2065', 'Starlight Ventures', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '4862', 'Starlight Ventures', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '1203', 'Nebula Navigators', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '4857', 'Cosmic Discoveries', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '2399', 'Starlight Ventures', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '3477', 'Astro Quest', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '3193', 'Galactic Explorers', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '3199', 'Astro Quest', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '2696', 'Starlight Ventures', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '3293', 'Stellar Ventures', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '4710', 'Orbit Explorers', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '4048', 'Galactic Explorers', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '1495', 'Celestial Explorations', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '2335', 'Orbit Explorers', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '3125', 'Orbit Explorers', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '3255', 'Galactic Explorers', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '4971', 'Cosmic Discoveries', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '4152', 'Stellar Ventures', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '1528', 'Orbit Explorers', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '1877', 'Orbit Explorers', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '4999', 'Galactic Explorers', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '1415', 'Interstellar Expeditions', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '3382', 'Galaxy Seekers', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '4308', 'Astro Quest', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '3164', 'Stellar Ventures', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '1984', 'Astro Quest', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '3263', 'Interstellar Expeditions', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '2188', 'Starlight Ventures', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '1480', 'Stellar Ventures', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '3209', 'Galaxy Seekers', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '4729', 'Stellar Ventures', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '1471', 'Stellar Ventures', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '1466', 'Interstellar Expeditions', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '2201', 'Interstellar Expeditions', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '2532', 'Cosmic Discoveries', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '4514', 'Stellar Ventures', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '1066', 'Astro Quest', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '4378', 'Celestial Explorations', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '4671', 'Galaxy Seekers', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '1017', 'Galaxy Seekers', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '3014', 'Galactic Explorers', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '1368', 'Interstellar Expeditions', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '3911', 'Celestial Explorations', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '1845', 'Interstellar Expeditions', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '4339', 'Galactic Explorers', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '1319', 'Cosmic Discoveries', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '1594', 'Nebula Navigators', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '4663', 'Starlight Ventures', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '1675', 'Stellar Ventures', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '3491', 'Galactic Explorers', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '3979', 'Astro Quest', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '3387', 'Astro Quest', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '3006', 'Orbit Explorers', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '1730', 'Interstellar Expeditions', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '4538', 'Cosmic Discoveries', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '1255', 'Celestial Explorations', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '4962', 'Interstellar Expeditions', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '1167', 'Interstellar Expeditions', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '4212', 'Galactic Explorers', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '2959', 'Starlight Ventures', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '2137', 'Stellar Ventures', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '3767', 'Galaxy Seekers', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '3699', 'Celestial Explorations', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '1515', 'Celestial Explorations', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '3831', 'Galactic Explorers', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '3511', 'Orbit Explorers', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '3396', 'Galaxy Seekers', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '1951', 'Interstellar Expeditions', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '1661', 'Galactic Explorers', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '4255', 'Orbit Explorers', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '2062', 'Cosmic Discoveries', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '3398', 'Interstellar Expeditions', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '2348', 'Celestial Explorations', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '1345', 'Galaxy Seekers', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '3782', 'Galaxy Seekers', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '1523', 'Interstellar Expeditions', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '2252', 'Galactic Explorers', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '2844', 'Galactic Explorers', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '2022', 'Celestial Explorations', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '1241', 'Stellar Ventures', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '1020', 'Cosmic Discoveries', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '4957', 'Galaxy Seekers', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '3698', 'Galaxy Seekers', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '3128', 'Celestial Explorations', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '3198', 'Celestial Explorations', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '3099', 'Starlight Ventures', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '3461', 'Starlight Ventures', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '4574', 'Galaxy Seekers', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '3041', 'Celestial Explorations', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '3951', 'Astro Quest', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '3716', 'Astro Quest', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '3451', 'Interstellar Expeditions', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '1341', 'Cosmic Discoveries', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '1323', 'Astro Quest', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '3496', 'Cosmic Discoveries', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '1825', 'Galactic Explorers', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '2099', 'Nebula Navigators', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '2246', 'Interstellar Expeditions', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '2364', 'Galactic Explorers', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '3265', 'Cosmic Discoveries', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '2913', 'Stellar Ventures', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '4621', 'Galactic Explorers', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '2757', 'Galaxy Seekers', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '3876', 'Cosmic Discoveries', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '2290', 'Astro Quest', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '3854', 'Nebula Navigators', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '1518', 'Celestial Explorations', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '3452', 'Astro Quest', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '2991', 'Interstellar Expeditions', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '2324', 'Stellar Ventures', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '3910', 'Nebula Navigators', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '2334', 'Nebula Navigators', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '1917', 'Galaxy Seekers', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '4135', 'Galaxy Seekers', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '2263', 'Orbit Explorers', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '1939', 'Galaxy Seekers', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '3582', 'Nebula Navigators', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '3029', 'Stellar Ventures', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '3782', 'Nebula Navigators', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '4438', 'Starlight Ventures', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '3944', 'Galactic Explorers', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '4070', 'Stellar Ventures', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '2205', 'Celestial Explorations', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '4893', 'Starlight Ventures', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '3007', 'Stellar Ventures', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '1125', 'Astro Quest', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '2399', 'Orbit Explorers', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '4770', 'Stellar Ventures', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '2769', 'Celestial Explorations', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '3704', 'Cosmic Discoveries', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '3425', 'Orbit Explorers', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '1880', 'Nebula Navigators', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '3382', 'Interstellar Expeditions', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '3312', 'Interstellar Expeditions', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '1425', 'Stellar Ventures', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '3564', 'Cosmic Discoveries', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '4337', 'Starlight Ventures', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '3369', 'Cosmic Discoveries', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '4903', 'Orbit Explorers', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '3442', 'Cosmic Discoveries', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '1440', 'Nebula Navigators', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '2496', 'Starlight Ventures', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '2989', 'Nebula Navigators', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '3934', 'Cosmic Discoveries', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '1607', 'Cosmic Discoveries', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '4382', 'Orbit Explorers', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '2704', 'Galactic Explorers', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '1804', 'Astro Quest', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '2552', 'Stellar Ventures', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '3601', 'Galactic Explorers', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '4488', 'Galactic Explorers', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '2529', 'Astro Quest', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '2012', 'Galaxy Seekers', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '1363', 'Nebula Navigators', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '1899', 'Cosmic Discoveries', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '1919', 'Interstellar Expeditions', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '2752', 'Astro Quest', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '1107', 'Nebula Navigators', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '3012', 'Starlight Ventures', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '3990', 'Celestial Explorations', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '2838', 'Celestial Explorations', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '2340', 'Celestial Explorations', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '1300', 'Stellar Ventures', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '2350', 'Celestial Explorations', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '3196', 'Galaxy Seekers', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '3833', 'Nebula Navigators', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '2292', 'Cosmic Discoveries', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '3386', 'Starlight Ventures', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '4209', 'Galaxy Seekers', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '2230', 'Galaxy Seekers', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '4044', 'Nebula Navigators', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '1937', 'Orbit Explorers', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '1234', 'Cosmic Discoveries', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '1240', 'Orbit Explorers', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '2888', 'Galactic Explorers', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '2433', 'Celestial Explorations', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '4063', 'Starlight Ventures', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '4447', 'Astro Quest', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '4405', 'Orbit Explorers', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '4967', 'Starlight Ventures', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '4056', 'Galactic Explorers', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '1368', 'Interstellar Expeditions', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '2363', 'Interstellar Expeditions', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '1847', 'Stellar Ventures', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '4455', 'Starlight Ventures', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '1063', 'Celestial Explorations', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '1999', 'Galaxy Seekers', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '2354', 'Stellar Ventures', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '2084', 'Starlight Ventures', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '4670', 'Starlight Ventures', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '1489', 'Astro Quest', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '3596', 'Galaxy Seekers', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '2346', 'Galactic Explorers', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '4205', 'Galactic Explorers', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '4740', 'Galactic Explorers', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '2143', 'Interstellar Expeditions', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '2128', 'Interstellar Expeditions', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '3280', 'Galaxy Seekers', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '4229', 'Galactic Explorers', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '3286', 'Orbit Explorers', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '4041', 'Stellar Ventures', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '4469', 'Galaxy Seekers', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '2066', 'Cosmic Discoveries', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '3835', 'Galactic Explorers', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '3511', 'Orbit Explorers', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '2239', 'Stellar Ventures', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '3140', 'Nebula Navigators', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '1827', 'Orbit Explorers', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '1586', 'Cosmic Discoveries', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '4967', 'Stellar Ventures', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '3210', 'Cosmic Discoveries', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '1405', 'Galactic Explorers', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '2024', 'Galaxy Seekers', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '2277', 'Nebula Navigators', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '3510', 'Astro Quest', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '2806', 'Orbit Explorers', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '2046', 'Starlight Ventures', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '1264', 'Starlight Ventures', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '4913', 'Celestial Explorations', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '4872', 'Nebula Navigators', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '3531', 'Orbit Explorers', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '3849', 'Orbit Explorers', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '1588', 'Galactic Explorers', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '1728', 'Galactic Explorers', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '3882', 'Nebula Navigators', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '4568', 'Orbit Explorers', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '4086', 'Celestial Explorations', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '2624', 'Stellar Ventures', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '3538', 'Stellar Ventures', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '3843', 'Cosmic Discoveries', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '4432', 'Stellar Ventures', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '4661', 'Nebula Navigators', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '1419', 'Nebula Navigators', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '3225', 'Astro Quest', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '1672', 'Stellar Ventures', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '3896', 'Stellar Ventures', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '3561', 'Nebula Navigators', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '2720', 'Nebula Navigators', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '1882', 'Stellar Ventures', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '2010', 'Celestial Explorations', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '3862', 'Starlight Ventures', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '3161', 'Galactic Explorers', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '1749', 'Galaxy Seekers', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '1634', 'Astro Quest', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '4387', 'Astro Quest', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '3155', 'Orbit Explorers', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '3760', 'Starlight Ventures', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '2759', 'Orbit Explorers', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '4566', 'Cosmic Discoveries', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '3695', 'Interstellar Expeditions', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '3806', 'Orbit Explorers', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '1277', 'Galactic Explorers', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '2401', 'Interstellar Expeditions', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '4877', 'Starlight Ventures', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '3847', 'Galaxy Seekers', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '3026', 'Celestial Explorations', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '4105', 'Interstellar Expeditions', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '3727', 'Cosmic Discoveries', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '4241', 'Cosmic Discoveries', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '3477', 'Galactic Explorers', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '2678', 'Galactic Explorers', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '3654', 'Nebula Navigators', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '1342', 'Orbit Explorers', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '2252', 'Orbit Explorers', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '3328', 'Galactic Explorers', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '2218', 'Celestial Explorations', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '2605', 'Celestial Explorations', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '3819', 'Galaxy Seekers', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '2733', 'Stellar Ventures', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '1625', 'Celestial Explorations', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '3423', 'Cosmic Discoveries', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '4070', 'Galaxy Seekers', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '4718', 'Astro Quest', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '1850', 'Interstellar Expeditions', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '4569', 'Galactic Explorers', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '3396', 'Interstellar Expeditions', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '2983', 'Galactic Explorers', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '4446', 'Galaxy Seekers', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '2980', 'Orbit Explorers', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '3943', 'Cosmic Discoveries', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '1008', 'Nebula Navigators', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '2187', 'Orbit Explorers', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '1777', 'Interstellar Expeditions', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '1418', 'Interstellar Expeditions', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '1600', 'Orbit Explorers', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '1409', 'Cosmic Discoveries', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '2270', 'Orbit Explorers', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '1971', 'Stellar Ventures', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '1310', 'Interstellar Expeditions', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '4170', 'Stellar Ventures', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '2552', 'Celestial Explorations', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '4838', 'Astro Quest', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '2108', 'Orbit Explorers', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '2214', 'Celestial Explorations', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '3676', 'Astro Quest', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '2149', 'Celestial Explorations', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '4331', 'Starlight Ventures', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '1361', 'Cosmic Discoveries', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '4443', 'Orbit Explorers', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '4479', 'Celestial Explorations', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '2266', 'Nebula Navigators', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '2161', 'Starlight Ventures', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '1492', 'Starlight Ventures', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '1084', 'Starlight Ventures', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '4982', 'Interstellar Expeditions', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '4005', 'Starlight Ventures', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '2554', 'Galaxy Seekers', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '3308', 'Orbit Explorers', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '2821', 'Stellar Ventures', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '2548', 'Galaxy Seekers', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '2077', 'Stellar Ventures', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '1492', 'Orbit Explorers', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '2270', 'Stellar Ventures', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '2322', 'Galactic Explorers', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '1092', 'Astro Quest', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '1366', 'Orbit Explorers', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '2500', 'Cosmic Discoveries', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '3003', 'Starlight Ventures', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '2282', 'Cosmic Discoveries', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '3433', 'Starlight Ventures', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '2845', 'Interstellar Expeditions', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '1788', 'Celestial Explorations', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '4014', 'Interstellar Expeditions', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '3434', 'Celestial Explorations', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '4306', 'Galaxy Seekers', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '1767', 'Stellar Ventures', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '4681', 'Stellar Ventures', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '3565', 'Cosmic Discoveries', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '1987', 'Galaxy Seekers', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '2403', 'Starlight Ventures', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '2207', 'Cosmic Discoveries', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '3686', 'Nebula Navigators', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '2903', 'Astro Quest', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '4817', 'Cosmic Discoveries', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '1107', 'Interstellar Expeditions', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '3024', 'Astro Quest', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '2964', 'Starlight Ventures', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '2111', 'Cosmic Discoveries', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '4331', 'Interstellar Expeditions', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '2445', 'Nebula Navigators', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '4815', 'Cosmic Discoveries', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '4943', 'Starlight Ventures', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '4022', 'Starlight Ventures', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '3221', 'Starlight Ventures', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '4454', 'Orbit Explorers', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '2071', 'Galaxy Seekers', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '4727', 'Starlight Ventures', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '4808', 'Celestial Explorations', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '2830', 'Orbit Explorers', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '2253', 'Starlight Ventures', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '3387', 'Starlight Ventures', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '2501', 'Interstellar Expeditions', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '4063', 'Orbit Explorers', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '4986', 'Stellar Ventures', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '3987', 'Galactic Explorers', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '3941', 'Nebula Navigators', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '3669', 'Orbit Explorers', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '4039', 'Celestial Explorations', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '4488', 'Stellar Ventures', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '2119', 'Galactic Explorers', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '4403', 'Celestial Explorations', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '2149', 'Celestial Explorations', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '4300', 'Cosmic Discoveries', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '3717', 'Galaxy Seekers', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '4395', 'Galactic Explorers', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '1343', 'Astro Quest', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '2000', 'Galaxy Seekers', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '3217', 'Nebula Navigators', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '1685', 'Galaxy Seekers', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '2769', 'Galactic Explorers', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '1297', 'Celestial Explorations', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '2482', 'Astro Quest', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '2604', 'Interstellar Expeditions', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '2184', 'Galactic Explorers', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '1960', 'Astro Quest', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '3160', 'Interstellar Expeditions', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '1634', 'Orbit Explorers', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '3952', 'Stellar Ventures', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '3497', 'Galaxy Seekers', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '2688', 'Stellar Ventures', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '1474', 'Galaxy Seekers', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '4283', 'Galactic Explorers', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '2887', 'Galactic Explorers', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '1688', 'Stellar Ventures', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '2514', 'Astro Quest', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '2021', 'Cosmic Discoveries', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '4793', 'Galaxy Seekers', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '3611', 'Stellar Ventures', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '1403', 'Starlight Ventures', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '1442', 'Orbit Explorers', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '1967', 'Galactic Explorers', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '4832', 'Astro Quest', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '3878', 'Celestial Explorations', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '4989', 'Galactic Explorers', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '2162', 'Cosmic Discoveries', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '2160', 'Interstellar Expeditions', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '2070', 'Galaxy Seekers', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '1203', 'Celestial Explorations', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '4440', 'Stellar Ventures', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '2348', 'Celestial Explorations', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '4706', 'Nebula Navigators', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '4124', 'Galaxy Seekers', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '3979', 'Astro Quest', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '2772', 'Nebula Navigators', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '1246', 'Galactic Explorers', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '4080', 'Celestial Explorations', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '2461', 'Orbit Explorers', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '2458', 'Interstellar Expeditions', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '1970', 'Astro Quest', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '2219', 'Orbit Explorers', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '4712', 'Starlight Ventures', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '4433', 'Celestial Explorations', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '4047', 'Orbit Explorers', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '3701', 'Galaxy Seekers', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '1513', 'Starlight Ventures', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '2992', 'Astro Quest', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '2514', 'Celestial Explorations', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '4218', 'Celestial Explorations', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '2914', 'Galaxy Seekers', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '4870', 'Interstellar Expeditions', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '3864', 'Astro Quest', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '1961', 'Nebula Navigators', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '3487', 'Starlight Ventures', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '2246', 'Interstellar Expeditions', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '1213', 'Galaxy Seekers', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '3940', 'Interstellar Expeditions', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '1473', 'Interstellar Expeditions', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '1184', 'Stellar Ventures', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '3241', 'Starlight Ventures', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '2389', 'Nebula Navigators', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '1682', 'Starlight Ventures', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '3836', 'Starlight Ventures', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '3221', 'Nebula Navigators', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '3206', 'Orbit Explorers', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '2079', 'Starlight Ventures', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '1517', 'Celestial Explorations', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '3056', 'Astro Quest', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '2075', 'Astro Quest', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '3554', 'Orbit Explorers', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '3662', 'Astro Quest', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '1209', 'Celestial Explorations', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '2876', 'Astro Quest', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '2425', 'Astro Quest', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '3956', 'Interstellar Expeditions', 'colonization');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '4968', 'Orbit Explorers', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '3084', 'Astro Quest', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '2340', 'Galactic Explorers', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '4937', 'Nebula Navigators', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '1432', 'Astro Quest', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Stellar Quest', '2933', 'Astro Quest', 'communication');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '2459', 'Galaxy Seekers', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '4326', 'Nebula Navigators', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '2209', 'Galactic Explorers', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '3667', 'Astro Quest', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Celestial Discovery', '4174', 'Orbit Explorers', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Star Voyager', '3634', 'Nebula Navigators', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '3640', 'Galaxy Seekers', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '1321', 'Orbit Explorers', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '3070', 'Astro Quest', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '4888', 'Galaxy Seekers', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '4493', 'Interstellar Expeditions', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '1834', 'Cosmic Discoveries', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '2339', 'Orbit Explorers', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '3697', 'Astro Quest', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '4817', 'Cosmic Discoveries', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Galaxy Quest', '4891', 'Galactic Explorers', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '2473', 'Galaxy Seekers', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '3091', 'Celestial Explorations', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Orion Odyssey', '2232', 'Stellar Ventures', 'celestial body sample return');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Nebula Expedition', '2159', 'Galaxy Seekers', 'asteroid mining');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '4625', 'Starlight Ventures', 'technology demonstration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Lunar Legacy', '1213', 'Orbit Explorers', 'satellite deployment');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '1841', 'Astro Quest', 'space tourism');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Apollo 11', '3969', 'Stellar Ventures', 'scientific research');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '1433', 'Orbit Explorers', 'orbital debris removal');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Cosmic Crusade', '1033', 'Astro Quest', 'exploration');
INSERT INTO stellar_missions (mission_name, launch_year, agency, purpose) VALUES ('Solar Sojourn', '4612', 'Starlight Ventures', 'space tourism');